### ISSUE TITLE
Problem when initializing

### ISSUE THREAD

**Issue by markoshorro** [franrua/conf_files#1]
Your emacs configuration does not work if elpa directory is not initialized. I think you should also consider this case.

**Comment by franrua** [comment]
As indicated in comments, is the folder where I save the packages, but it depends of the emacs version, and you must change it if your package folder is different.
Anyway, I added a new couple of lines that creates the folder if it haven't been created yet. I hope this will solve the problem you have.

**Comment by markoshorro** [comment]
I think it should. Thanks ;)
